[package]
name = "subterranean"
version = "0.1.0"
authors = ["Akihiro Takai <at.sisy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.0"
toml = "0.5.5"
serde = { version = "1.0", features = ["derive"] }

[profile.dev]
opt-level = 3

[dependencies.torifune]
path = "../torifune"