[package]
name = "suzu"
version = "0.1.0"
authors = ["Akihiro Takai <at.sisy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.5"
collision = "0.20.1"
serde = { version = "1.0", features = ["derive"] }
cgmath = "0.17.0"
rand = "0.7.2"
num = "*"
number_to_jk = { git = "https://github.com/atsisy/number_to_jk.git" }

[profile.dev]
opt-level = 3

[dependencies.ggez]
path = "../ggez"

[dependencies.torifune]
path = "../torifune"

[dependencies.tiled]
path = "../rs-tiled"