texture_paths = [
              "/ghost1.png",
              "/lotus_pink.png",
              "/lotus_blue.png",
              "/lotus_yellow.png",
              "/textures/text_back.png",
              "/textures/paper1.jpg",
              "/textures/paper2.jpg",
              "/textures/large_book1.png",
              "/textures/large_book2.png",
              "/textures/large_book3.png",
              "/textures/middle_book1.png",
              "/textures/middle_book2.png",
              "/textures/middle_book3.png",
              "/textures/wood1.png",
	      "/textures/wafu_texture1.jpg",
	      "/textures/wafu_texture2.jpg",
	      "/textures/chobo.png",
	      "/textures/choice_panel1.png",
	      "/textures/choice_panel2.png",
	      "/textures/choice_panel3.png",
	      "/textures/choice_panel4.png",
	      "/textures/choice_panel5.png",
	      "/textures/junko_tachie_default.png",
	      "/textures/sight_background1.png",
	      "/textures/arrow_right.png",
	      "/textures/arrow_left.png",
	      "/textures/kosuzu_front1.png",
	      "/textures/kosuzu_front2.png",
	      "/textures/kosuzu_front3.png",
	      "/textures/kosuzu_back1.png",
	      "/textures/kosuzu_back2.png",
	      "/textures/kosuzu_back3.png",
	      "/textures/kosuzu_right1.png",
	      "/textures/kosuzu_right2.png",
	      "/textures/kosuzu_right3.png",
	      "/textures/kosuzu_left1.png",
	      "/textures/kosuzu_left2.png",
	      "/textures/kosuzu_left3.png",	      
	      "/textures/store_button.png",
	      "/textures/reset_button.png",
	      "/textures/menu_art1.png",
	      "/textures/menu_art2.png",
	      "/textures/jp_house_background1.png",
	      "/textures/book_box_front.png",
	      "/textures/book_box_back.png",
	      "/textures/paper3.jpg",
	      "/textures/paper4.jpg",
	      "/textures/paper5.jpg",
	      "/textures/paper6.jpg",
	      "/textures/paper7.jpg",
	      "/textures/clock1.png",
	      "/textures/clock_needle1.png",
	      "/textures/clock_short_needle.png",
	      "/textures/hanko.png",
	      "/textures/next_line_icon.png",
	      "/textures/large_book_scratch_fair1.png",
	      "/textures/large_book_scratch_fair2.png",
	      "/textures/large_book_scratch_fair3.png",
	      "/textures/large_book_scratch_fair4.png",
	      "/textures/large_book_scratch_bad1.png",	
	      "/textures/large_book_scratch_bad2.png",
	      "/textures/large_book_scratch_bad3.png",
	      "/textures/large_book_scratch_bad4.png",
	      "/textures/manual_title_detail_page.png",
	      "/textures/manual_borrowing_flow.png",
	      "/textures/manual_return_flow.png",
	      "/textures/page_edge_left.png",
	      "/textures/page_edge_right.png",
	      ]
font_paths = ["/fonts/azuki.ttf", "/fonts/RiiT_F.ttf", "/fonts/OradanoGSRR.ttf", "/fonts/cinecaption226.ttf"]
tileset_paths = ["./resources/maps/suzunaan2/main.tmx"]
scenario_table_path = "./resources/scenario_table.toml"
customers_name = ["霧雨魔里沙", "稗田阿求", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]
sound_file_path = ["/sound/bgm/title.mp3", "/sound/se/turn_the_page.wav"]

[[map_information]]
id = 1
comment = "鈴奈庵マップ1"
map_file_path = "./resources/maps/suzunaan2/main.tmx"
event_map_file_path = "./resources/event_map1.toml"

[[books_information]]
name = "テスト本 壱"
pages = 128
size = "大判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "テスト本 弐"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "テスト本 参"
pages = 128
size = "大判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "テスト本 肆"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "テスト本 伍"
pages = 128
size = "大判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "テスト本 陸"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "テスト本 漆"
pages = 128
size = "大判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "テスト本 捌"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "テスト本 玖"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "テスト本 拾"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "越中史料"
pages = 128
size = "中判本"
billing_number = 2
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "尾張名所図会"
pages = 128
size = "中判本"
billing_number = 2
base_price = 100
condition = "Good"
unique_id = 0

# 啓蒙, 思想 3
[[books_information]]
name = "改暦弁"
pages = 128
size = "中判本"
billing_number = 3
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "善の研究"
pages = 128
size = "中判本"
billing_number = 3
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "学問のすゝめ"
pages = 128
size = "中判本"
billing_number = 3
base_price = 100
condition = "Good"
unique_id = 0

# 見聞録 4
[[books_information]]
name = "さへづり草"
pages = 128
size = "中判本"
billing_number = 4
base_price = 100
condition = "Good"
unique_id = 0

# 小説, 物語 5
[[books_information]]
name = "通俗伊蘇普物語"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "北越奇談"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "名所江戸百景"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "絵本百物語"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "狂歌百物語"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "遠野物語"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "名将言行録"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "幕末百話"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

# 宗教 6
[[books_information]]
name = "明治元訳聖書"
pages = 128
size = "中判本"
billing_number = 6
base_price = 100
condition = "Good"
unique_id = 0

[[sprite_batch_information]]
sprite_x_size = 16
sprite_y_size = 16
path = "/tile_textures/black1.png"

[[sprite_batch_information]]
sprite_x_size = 16
sprite_y_size = 16
path = "/tile_textures/red1.png"

[[sprite_batch_information]]
sprite_x_size = 64
sprite_y_size = 64
path = "/tile_textures/menu_art2.png"

[[sprite_batch_information]]
sprite_x_size = 128
sprite_y_size = 128
path = "/tile_textures/menu_art3.png"

[[sprite_batch_information]]
sprite_x_size = 128
sprite_y_size = 128
path = "/tile_textures/shoji.png"

[[sprite_batch_information]]
sprite_x_size = 64
sprite_y_size = 64
path = "/tile_textures/black_frame.png"

[[sprite_batch_information]]
sprite_x_size = 64
sprite_y_size = 64
path = "/tile_textures/black_frame2.png"

[ad_cost_table]
ShopNobori = 100
TownNobori = 100
Chindon = 100
NewsPaper = 100
BunBunMaruPaper = 100
AdPaper = 100