texture_paths = [
              "/ghost1.png",
              "/lotus_pink.png",
              "/lotus_blue.png",
              "/lotus_yellow.png",
              "/text_back.png",
              "/textures/paper1.jpg",
              "/textures/paper2.jpg",
              "/textures/large_book1.png",
              "/textures/large_book2.png",
              "/textures/large_book3.png",
              "/textures/middle_book1.png",
              "/textures/middle_book2.png",
              "/textures/middle_book3.png",
              "/textures/wood1.jpg",
	      "/textures/wafu_texture1.jpg",
	      "/textures/chobo.png",
	      "/textures/choice_panel1.png",
	      "/textures/choice_panel2.png",
	      "/textures/choice_panel3.png",
	      "/textures/choice_panel4.png",
	      "/textures/choice_panel5.png"]
font_paths = ["/fonts/azuki.ttf", "/fonts/RiiT_F.ttf"]
tileset_paths = ["./resources/test.tmx"]
customers_name = ["霧雨魔里沙", "すみれの隣人"]

[[books_information]]
name = "テスト本1"
pages = 128
size = "大判本"

[[books_information]]
name = "テスト本2"
pages = 128
size = "中判本"