texture_paths = [
              "/ghost1.png",
              "/lotus_pink.png",
              "/lotus_blue.png",
              "/lotus_yellow.png",
              "/text_back.png",
              "/textures/paper1.jpg",
              "/textures/paper2.jpg",
              "/textures/large_book1.png",
              "/textures/large_book2.png",
              "/textures/large_book3.png",
              "/textures/middle_book1.png",
              "/textures/middle_book2.png",
              "/textures/middle_book3.png",
              "/textures/wood1.png",
	      "/textures/wafu_texture1.jpg",
	      "/textures/wafu_texture2.jpg",
	      "/textures/chobo.png",
	      "/textures/choice_panel1.png",
	      "/textures/choice_panel2.png",
	      "/textures/choice_panel3.png",
	      "/textures/choice_panel4.png",
	      "/textures/choice_panel5.png",
	      "/textures/junko_tachie_default.png",
	      "/textures/sight_background1.png"]
font_paths = ["/fonts/azuki.ttf", "/fonts/RiiT_F.ttf"]
tileset_paths = ["./resources/test.tmx"]
customers_name = ["霧雨魔里沙", "稗田阿求"]

[[map_information]]
id = 1
comment = "鈴奈庵マップ1"
map_file_path = "./resources/map1.tmx"
event_map_file_path = "./resources/event_map1.toml"

[[books_information]]
name = "テスト本1"
pages = 128
size = "大判本"

[[books_information]]
name = "テスト本2"
pages = 128
size = "中判本"