[[event-panel]]
type = "text"
trigger = "action"
text = "イベント発生!!"
[event-panel.position]
x = 20
y = 0

[[event-panel]]
type = "switch-scene"
trigger = "action"
switch-scene-id = "MainDesk"
[event-panel.position]
x = 1
y = 10

[[event-panel]]
type = "book-shelf"
trigger = "action"
[event-panel.shelf-info]
begin-number = 700
end-number = 800
[event-panel.position]
x = 6
y = 3

[[event-panel]]
type = "builtin-event"
trigger = "action"
[event-panel.builtin-event-info]
symbol = "select-shelving-book"	
[event-panel.position]
x = 1
y = 12

[[event-panel]]
type = "builtin-event"
trigger = "action"
[event-panel.builtin-event-info]
symbol = "select-shelving-book"	
[event-panel.position]
x = 2
y = 13

[[event-panel]]
type = "builtin-event"
trigger = "action"
[event-panel.builtin-event-info]
symbol = "select-shelving-book"	
[event-panel.position]
x = 3
y = 12