[[event-panel]]
type = "text"
trigger = "action"
text = "イベント発生!!"
[event-panel.position]
x = 20
y = 0

[[event-panel]]
type = "switch-scene"
trigger = "action"
switch-scene-id = "MainDesk"
[event-panel.position]
x = 2
y = 14

[[event-panel]]
type = "book-shelf"
trigger = "action"
[event-panel.shelf-info]
begin-number = 1
end-number = 2
[event-panel.position]
x = 6
y = 3

[[event-panel]]
type = "book-shelf"
trigger = "action"
[event-panel.shelf-info]
begin-number = 1
end-number = 2
[event-panel.position]
x = 7
y = 3

[[event-panel]]
type = "book-shelf"
trigger = "action"
[event-panel.shelf-info]
begin-number = 3
end-number = 4
[event-panel.position]
x = 8
y = 3

[[event-panel]]
type = "book-shelf"
trigger = "action"
[event-panel.shelf-info]
begin-number = 3
end-number = 4
[event-panel.position]
x = 9
y = 3

[[event-panel]]
type = "book-shelf"
trigger = "action"
[event-panel.shelf-info]
begin-number = 5
end-number = 6
[event-panel.position]
x = 10
y = 3

[[event-panel]]
type = "book-shelf"
trigger = "action"
[event-panel.shelf-info]
begin-number = 5
end-number = 6
[event-panel.position]
x = 11
y = 3

[[event-panel]]
type = "builtin-event"
trigger = "action"
[event-panel.builtin-event-info]
symbol = "select-shelving-book"	
[event-panel.position]
x = 2
y = 16

[[event-panel]]
type = "builtin-event"
trigger = "action"
[event-panel.builtin-event-info]
symbol = "select-shelving-book"	
[event-panel.position]
x = 3
y = 16

[[event-panel]]
type = "builtin-event"
trigger = "action"
[event-panel.builtin-event-info]
symbol = "select-shelving-book"	
[event-panel.position]
x = 3
y = 17