texture_paths = [
              "/ghost1.png",
              "/lotus_pink.png",
              "/lotus_blue.png",
              "/lotus_yellow.png",
              "/textures/text_back.png",
              "/textures/paper1.png",
              "/textures/paper2.png",
              "/textures/large_book1.png",
              "/textures/large_book2.png",
              "/textures/large_book3.png",
              "/textures/middle_book1.png",
              "/textures/middle_book2.png",
              "/textures/middle_book3.png",
              "/textures/wood1.png",
	      "/textures/wafu_texture1.png",
	      "/textures/wafu_texture2.png",
	      "/textures/chobo.png",
	      "/textures/choice_panel1.png",
	      "/textures/choice_panel2.png",
	      "/textures/choice_panel3.png",
	      "/textures/choice_panel4.png",
	      "/textures/choice_panel5.png",
	      "/textures/junko_tachie_default.png",
	      "/textures/sight_background1.png",
	      "/textures/arrow_right.png",
	      "/textures/arrow_left.png",
	      "/textures/kosuzu_front1.png",
	      "/textures/kosuzu_front2.png",
	      "/textures/kosuzu_front3.png",
	      "/textures/kosuzu_back1.png",
	      "/textures/kosuzu_back2.png",
	      "/textures/kosuzu_back3.png",
	      "/textures/kosuzu_right1.png",
	      "/textures/kosuzu_right2.png",
	      "/textures/kosuzu_right3.png",
	      "/textures/kosuzu_left1.png",
	      "/textures/kosuzu_left2.png",
	      "/textures/kosuzu_left3.png",  
	      "/textures/store_button.png",
	      "/textures/reset_button.png",
	      "/textures/menu_art1.png",
	      "/textures/menu_art2.png",
	      "/textures/jp_house_background1.png",
	      "/textures/book_box_front.png",
	      "/textures/book_box_back.png",
	      "/textures/paper3.png",
	      "/textures/paper4.png",
	      "/textures/paper5.png",
	      "/textures/paper6.png",
	      "/textures/paper7.png",
	      "/textures/clock1.png",
	      "/textures/clock_needle1.png",
	      "/textures/clock_short_needle.png",
	      "/textures/hanko.png",
	      "/textures/next_line_icon.png",
	      "/textures/large_book_scratch_fair1.png",
	      "/textures/large_book_scratch_fair2.png",
	      "/textures/large_book_scratch_fair3.png",
	      "/textures/large_book_scratch_fair4.png",
	      "/textures/large_book_scratch_bad1.png",	
	      "/textures/large_book_scratch_bad2.png",
	      "/textures/large_book_scratch_bad3.png",
	      "/textures/large_book_scratch_bad4.png",
	      "/textures/manual_title_detail_page.png",
	      "/textures/manual_borrowing_flow.png",
	      "/textures/manual_return_flow.png",
	      "/textures/page_edge_left.png",
	      "/textures/page_edge_right.png",
	      "/textures/library.png",
	      "/textures/kosuzu.png",
	      "/textures/circle.png",
	      "/textures/money_box.png",
	      "/textures/kosuzu_smile1.png",
	      "/textures/100yen.png",
	      "/textures/50yen.png",
	      "/textures/500yen.png",
	      "/textures/bara.png",
   	      "/textures/suzunaan_map.png",
	      "/textures/mob1_default.png",
	      "/textures/logo.png",
	      "/textures/akyu_default.png",
	      "/textures/pixel_character/mob1/front1.png",
	      "/textures/pixel_character/mob1/front2.png",
	      "/textures/pixel_character/mob1/front3.png",
	      "/textures/pixel_character/mob1/back1.png",
	      "/textures/pixel_character/mob1/back2.png",
	      "/textures/pixel_character/mob1/back3.png",
	      "/textures/pixel_character/mob1/right1.png",
	      "/textures/pixel_character/mob1/right2.png",
	      "/textures/pixel_character/mob1/right3.png",
	      "/textures/pixel_character/mob1/left1.png",
	      "/textures/pixel_character/mob1/left2.png",
	      "/textures/pixel_character/mob1/left3.png",
	      "/textures/page_edge_left_not_alpha.png",
	      "/textures/page_edge_right_not_alpha.png",
	      ]
font_paths = ["/fonts/azuki.ttf", "/fonts/RiiT_F.ttf", "/fonts/OradanoGSRR.ttf", "/fonts/cinecaption226.ttf", "/fonts/JF-Dot-ShinonomeMaru12B.ttf"]
tileset_paths = ["/maps/suzunaan2/main.tmx"]
scenario_table_path = "/scenario_table.toml"
daily_customer_dist_path = "/daily_customer_dist.toml"
customers_name = ["マリ", "さくら", "千代", "ハル", "ハナ", "はる", "スズコ", "文子", "タエコ", "ユリ", "ユイ", "ヨウコ", "アサ"]
sound_file_path = [
		"/sound/bgm/title.mp3",
		"/sound/se/turn_the_page.wav",
		"/sound/se/onjin/bell.mp3",
		"/sound/se/se_lab/message.mp3",
		]

[[map_information]]
id = 1
comment = "鈴奈庵マップ1"
map_file_path = "./resources/maps/suzunaan2/main.tmx"
event_map_file_path = "/event_map1.toml"

[[books_information]]
name = "女大学"
pages = 128
size = "大判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "春雨物語"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "雨月物語"
pages = 128
size = "大判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "団子屋図解"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "養生訓"
pages = 128
size = "大判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "奥の細道"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "野ざらし紀行"
pages = 128
size = "大判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "古事記傳 一"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Bad"
unique_id = 0

[[books_information]]
name = "古事記傳 二"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "古事記傳 三"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "古事記傳 四"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "古事記傳 五"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "テスト本 拾"
pages = 128
size = "中判本"
billing_number = 1
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "越中史料"
pages = 128
size = "中判本"
billing_number = 2
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "尾張名所図会"
pages = 128
size = "中判本"
billing_number = 2
base_price = 100
condition = "Good"
unique_id = 0

# 啓蒙, 思想 3
[[books_information]]
name = "改暦弁"
pages = 128
size = "中判本"
billing_number = 3
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "善の研究"
pages = 128
size = "中判本"
billing_number = 3
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "学問のすゝめ"
pages = 128
size = "中判本"
billing_number = 3
base_price = 100
condition = "Good"
unique_id = 0

# 見聞録 4
[[books_information]]
name = "さへづり草"
pages = 128
size = "中判本"
billing_number = 4
base_price = 100
condition = "Good"
unique_id = 0

# 小説, 物語 5
[[books_information]]
name = "通俗伊蘇普物語"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "北越奇談"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "名所江戸百景"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "絵本百物語"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "狂歌百物語"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "遠野物語"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "名将言行録"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

[[books_information]]
name = "幕末百話"
pages = 128
size = "中判本"
billing_number = 5
base_price = 100
condition = "Good"
unique_id = 0

# 宗教 6
[[books_information]]
name = "明治元訳聖書"
pages = 128
size = "中判本"
billing_number = 6
base_price = 100
condition = "Good"
unique_id = 0

[[sprite_batch_information]]
sprite_x_size = 16
sprite_y_size = 16
path = "/tile_textures/black1.png"

[[sprite_batch_information]]
sprite_x_size = 16
sprite_y_size = 16
path = "/tile_textures/red1.png"

[[sprite_batch_information]]
sprite_x_size = 64
sprite_y_size = 64
path = "/tile_textures/menu_art2.png"

[[sprite_batch_information]]
sprite_x_size = 128
sprite_y_size = 128
path = "/tile_textures/menu_art3.png"

[[sprite_batch_information]]
sprite_x_size = 128
sprite_y_size = 128
path = "/tile_textures/shoji.png"

[[sprite_batch_information]]
sprite_x_size = 64
sprite_y_size = 64
path = "/tile_textures/black_frame.png"

[[sprite_batch_information]]
sprite_x_size = 64
sprite_y_size = 64
path = "/tile_textures/black_frame2.png"

[ad_cost_table]
AdPaper = 500
ShopNobori = 1000
TownNobori = 1500
Chindon = 2000
NewsPaper = 3000
BunBunMaruPaper = 5000

[ad_gain_table]
AdPaper = 1
ShopNobori = 2
TownNobori = 3
Chindon = 4
NewsPaper = 5
BunBunMaruPaper = 6

[ad_agency_cost_table]
HakureiJinja = 10
KirisameMahoten = 50
GettoDango = 60
Kusuriya = 70
Hieda = 80
YamaJinja = 90

[ad_agency_gain_table]
HakureiJinja = 0
KirisameMahoten = 10
GettoDango = 1000
Kusuriya = 3000
Hieda = 8000
YamaJinja = 10000