using-tachie = ["LotusPink", "LotusBlue"]

[scene-transition]
scenario = 1
dream = 2
desk = 3

[[scenario-group]]
type = "scenario"
id = 10
next-id = 11
background = "SightBackground1"

   [scenario-group.default-text-attribute]
   fpc = 0.2
   font_scale = 32.0
   color = 0x000000ff
   	 
   [[scenario-group.text]]
   text = """テスト用テキスト
   """
   [[scenario-group.text]]
   text = """本居小鈴
   サンプルテキスト
   """
   [[scenario-group.text]]
   fpc = 0.1
   font_scale = 28.0
   color = 0xff0000ff
   text = "赤字"

   [[scenario-group.text]]
   id = 4
   text = """古明地さとり
   """

[[scenario-group]]
type = "choice"
background = "WafuTexture1"
id = 11
   [[scenario-group.choice-pattern]]
   pattern = "選択肢1"
   jump-id = 3
   [[scenario-group.choice-pattern]]
   pattern = "選択肢2"
   jump-id = 3
   [[scenario-group.choice-pattern]]
   pattern = "選択肢3"
   jump-id = 3

   