padding = 10.0

[position]
x = 150.0
y = 550.0

[normal_font]
FontID = "Cinema"
color = 0xff
[normal_font.scale]
x = 30.0
y = 30.0

[large_font]
FontID = "Cinema"
color = 0xff
[large_font.scale]
x = 30.0
y = 30.0

[[each_entry_data]]
text = "開演"
event-type = "SceneTransition"
next-scene = "Scenario"

[[each_entry_data]]
text = "再入場"
event-type = "SceneTransition"
next-scene = "Scenario"

[[each_entry_data]]
text = "蓄音機"
event-type = "NextContents"
next-contents-name = "init-menu"

[[each_entry_data]]
text = "設定"
event-type = "SceneTransition"
next-scene = "Scenario"

[[each_entry_data]]
text = "退場"
event-type = "NextContents"
next-contents-name = "init-menu" 