[[contents-list]]
name = "init-menu"
type = "VTextList"
src = "./resources/title_contents/init_menu.toml"

[[contents-list]]
name = "new-game-menu"
type = "VTextList"
src = "./resources/title_contents/new_game_menu.toml"

[[contents-list]]
name = "hard-menu"
type = "VTextList"
src = "./resources/title_contents/hard_menu.toml"

[[contents-list]]
name = "sound-player"
type = "TitleSoundPlayer"
src = "./resources/title_contents/sound_player.toml"

[[contents-list]]
name = "update-panel"
type = "UpdatePanel"
src = "./resources/title_contents/update_panel.toml"

[[contents-list]]
name = "config-panel"
type = "ConfigPanel"
src = "./resources/title_contents/config_panel.toml"