[[contents-list]]
name = "init-menu"
type = "VTextList"
src = "./resources/title_contents/init_menu.toml"

[[contents-list]]
name = "sound-player"
type = "TitleSoundPlayer"
src = "./resources/title_contents/sound_player.toml"
