first-scenario-id = 10

[scene-transition]
scenario = 1
dream = 2
save = 4

[[scenario-group]]
type = "scenario"
id = 10
next-id = 12
background = "SightBackground1"

[scenario-group.tachie-data]
right = "KosuzuTachie1"
left = "KosuzuTachie1"

   [scenario-group.default-text-attribute]
   fpc = 2.0
   font_scale = 32.0
   color = 0x000000ff

   [[scenario-group.text]]
   text_src_path = "./resources/scenario/7_23/1.txt"

[[scenario-group]]
type = "choice"
header_text = "サァ準備ができたわよ"
id = 11
   [scenario-group.tachie-data]
   right = "KosuzuTachie1"
   left = "KosuzuTachie1"

   [[scenario-group.choice-pattern]]
   pattern = "行動開始"
   jump-id = 13
   [[scenario-group.choice-pattern]]
   pattern = "状態確認"
   jump-id = 2
   [[scenario-group.choice-pattern]]
   pattern = "保存"
   jump-id = 4

[[scenario-group]]
type = "choice"
header_text = "宣伝の依頼、受注もやらないとネ"
id = 14
   [scenario-group.tachie-data]
   right = "KosuzuTachie1"
   left = "KosuzuTachie1"

   [[scenario-group.choice-pattern]]
   pattern = "完了"
   jump-id = 16

[[scenario-group]]
type = "wait"
id = 16
next-id = 11
opecode = "ShowMain"
background = "SightBackground1"


[[scenario-group]]
type = "builtin"
opecode = "StartSchedule"
id = 13
background = "SightBackground1"

[[scenario-group]]
type = "wait"
id = 12
next-id = 15
opecode = "ScheduleCheck"
background = "SightBackground1"

[[scenario-group]]
type = "wait"
id = 15
next-id = 14
opecode = "ShowAd"
background = "SightBackground1"

[scenario-group.tachie-data]
right = "KosuzuTachie1"
left = "KosuzuTachie1"
