first-scenario-id = 10

[scene-transition]
scenario = 1
dream = 2
save = 4

[[scenario-group]]
type = "scenario"
id = 10
next-id = 11
background = "SightBackground1"

[scenario-group.tachie-data]
right = "KosuzuTachie1"
left = "KosuzuTachie1"

   [scenario-group.default-text-attribute]
   fpc = 2.0
   font_scale = 32.0
   color = 0x000000ff

   [[scenario-group.text]]
   text_src_path = "./resources/scenario/general/no_enough_money.txt"

[[scenario-group]]
type = "wait"
id = 11
next-id = 12
opecode = "NextDay"
background = "SightBackground1"